//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataVehicles4.DataAccess.Users
{
    using System;
    using System.Collections.Generic;
    
    public partial class cache
    {
        public string id { get; set; }
        public Nullable<int> expire { get; set; }
        public byte[] value { get; set; }
    }
}
