//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataVehicles4.DataAccess.Users
{
    using System;
    using System.Collections.Generic;
    
    public partial class database_type
    {
        public database_type()
        {
            this.data_bases = new HashSet<data_bases>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<data_bases> data_bases { get; set; }
    }
}
