//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataVehicles4.DataAccess.Users
{
    using System;
    using System.Collections.Generic;
    
    public partial class restrict
    {
        public restrict()
        {
            this.user_has_restrict_fields = new HashSet<user_has_restrict_fields>();
            this.user_has_restrict = new HashSet<user_has_restrict>();
        }
    
        public int id { get; set; }
        public string field_name { get; set; }
        public string client_caption { get; set; }
        public int child_id { get; set; }
    
        public virtual ICollection<user_has_restrict_fields> user_has_restrict_fields { get; set; }
        public virtual ICollection<user_has_restrict> user_has_restrict { get; set; }
    }
}
