//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataVehicles4.DataAccess.Users
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_pivot
    {
        public int pivot_id { get; set; }
        public string pivot_name { get; set; }
        public int tabDatabaseId { get; set; }
        public string tabFieldsArrHeader { get; set; }
        public string tabFieldsArrLeft { get; set; }
        public string tabCritActive { get; set; }
        public string tabFieldsFilterArr { get; set; }
        public string tabFieldsSortArr { get; set; }
    
        public virtual user user { get; set; }
    }
}
