//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataVehicles4.DataAccess.Users
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.individual_info = new HashSet<individual_info>();
            this.user_has_restrict_fields = new HashSet<user_has_restrict_fields>();
            this.user_has_restrict = new HashSet<user_has_restrict>();
            this.user_pivot = new HashSet<user_pivot>();
            this.data_bases = new HashSet<data_bases>();
        }
    
        public int id { get; set; }
        public string login { get; set; }
        public string pwd_hash { get; set; }
        public string name { get; set; }
        public System.DateTime reg_date { get; set; }
        public int rights { get; set; }
        public int max_install { get; set; }
        public int cur_install { get; set; }
        public string lang { get; set; }
    
        public virtual ICollection<individual_info> individual_info { get; set; }
        public virtual ICollection<user_has_restrict_fields> user_has_restrict_fields { get; set; }
        public virtual ICollection<user_has_restrict> user_has_restrict { get; set; }
        public virtual ICollection<user_pivot> user_pivot { get; set; }
        public virtual ICollection<data_bases> data_bases { get; set; }
    }
}
