//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataVehicles4.DataAccess.Users
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_has_restrict
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int restrict_id { get; set; }
        public int value { get; set; }
        public int lft { get; set; }
        public int rgt { get; set; }
    
        public virtual data_bases data_bases { get; set; }
        public virtual restrict restrict { get; set; }
        public virtual user user { get; set; }
    }
}
